### ISSUE TITLE
你好，一直在找typecho同步插件，找到了这里

### ISSUE THREAD

**Issue by moxiaonai** [vfhky/WeiboSync#1]
请问在config.php中的回调地址应该填什么，另外你的appid&&appsecret暴露出来了

**Comment by vfhky** [comment]
哈哈，还真没注意，当时直接从线上blog同步上来的。

**Comment by vfhky** [comment]
哈哈，还真没注意，当时直接从线上blog同步上来的。

**Comment by vfhky** [comment]
回调地址写weibo开放平台填写的url，在typecho登录获取weibo的token成功后，会调用这个url。

**Comment by moxiaonai** [comment]
你的功能好着没，能同步新浪微博吗，我把key和secret改成我自己的，回调地址改成后台插件页的地址，微博登录地址栏可以获取到code，但是没有出现登录成功状态，也没有出现微博名称。测试也不能同步，不知道是哪里的问题

**Comment by vfhky** [comment]
效果就是这个 https://typecodes.com/mix/synweibophpmarkdownimgurl.html ，不过现在自己的博客改成了pelican，就没用这个插件了。回调地址不是后台插件页的地址，这个不能随便填。

**Comment by moxiaonai** [comment]
好的，我再试试

**Comment by moxiaonai** [comment]
还是得麻烦问一下，我看你的代码中的回调地址，填写的是域名/weibo，这是你新建了页面还是，点击微博登录以后会跳转到这个页面，插件页面的token是复制地址栏的code,粘贴过去的还是
![如图](http://i1.buimg.com/1949/fe582634f050edee.png)

**Comment by moxiaonai** [comment]
大哥  你git上代码是不是不完整啊，没找到这个文件啊regexmarkdownimgurl.php。不懂php啊，求指教

**Comment by vfhky** [comment]
那个url地址用weibo开放平台php的sdk搭建的服务，周末我再整理下吧，弄个完整的说明文档。

**Comment by moxiaonai** [comment]
好的 非常感谢

**Comment by moxiaonai** [comment]
大哥啥时候整理教程啊

**Comment by vfhky** [comment]
已经整理好了，增加了基于新浪微博开放平台的应用服务程序，具体可以看README文件。
