### ISSUE TITLE
看你更新了就完全照你做的，怎么就没效果了呢？

### ISSUE THREAD

**Issue by chenmo-tssz** [vfhky/WeiboSync#2]
能帮我看看问题出在哪了吗？

**Comment by vfhky** [comment]
[新浪微博开放平台](https://github.com/xiaosier/libweibo)把分享接口改了，我找时间调整下。

**Comment by vfhky** [comment]
你好，插件已经按照新浪微博官方接口要求做了修改，请按照README文件进行更新。

**Comment by chenmo-tssz** [comment]
你好，立马更新可用。谢谢。
不过发现是不是微博上只能获取本站的图片，不能拉取云存储上的图片。因为我用的是你的SCS插件，没有获取到图片。

**Comment by vfhky** [comment]
也就是如果图片的路径包含本站域名就能在微博正常显示，如果是没有那么就不会显示图片？
